### ISSUE TITLE
LAMMPS Squared Exponential Kernel

### ISSUE THREAD

**Issue by Basti1211** [mir-group/flare_pp#46]
Hello there,

I have tried experimenting with your introductory Colab file and thus tried out the squared-exponential kernel. If I try to write a mapped LAMMPS file, the file only contains some header lines and not the actual potential. I have seen that you commented in the code that this functionality still needs to be implemented. Do you have plans to implement this feature soon? Is there any other way to extract the trained model and use it in LAMMPS without mapping the coefficients? 

Thank you for your work!
Bastian Jäckl

**Comment by YuuuXie** [comment]
Hi @Basti1211 ,

If you are using the B2 (ACE) descriptors with the squared exponential kernel, then unfortunately we don't have a plan to implement it because there isn't a very efficient mapping technique that makes the potential performant as the inner product kernel does.

If you are using the two/three/four-body descriptors with squared exponential kernel, we only have the support in our python code, which is in the "flare" repo. And we don't have plan to extend it to our cpp code and SGP in the very near future.

Let me know if the inner product kernel also works in your problem.

Best,
Yu

**Comment by Basti1211** [comment]
Hi @YuuuXie,

thank you for the fast respone!

I want (and should) use ACE (B2,B3,B4...) descriptors combined with a GPR approach for an 1-element system. I have implemented my own tiny kernel learning approach for test purposes and a Laplace/Gauss kernel worked best. But I will for sure try out the inner product kernel.  

Best,
Bastian
